"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  # Navigation
  { on = "c", run = "arrow prev", desc = "Previous file" },
  { on = "t", run = "arrow next", desc = "Next file" },
  { on = "h", run = "leave", desc = "Back to the parent directory" },
  { on = "n", run = "enter", desc = "Enter the child directory" },
  # NOTE: The above keymaps shadowed the following defaults:
  # c: copy (with submenu)
  # t: tab creation
  # n: next found item
]
